"""empty message

Revision ID: e7f44ab7e824
Revises: 
Create Date: 2023-12-26 23:18:42.397966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7f44ab7e824'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)

    with op.batch_alter_table('weblog', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('baner',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weblog', schema=None) as batch_op:
        batch_op.alter_column('baner',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
